trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
    - "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azurerm-connection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)'
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azurerm-connection'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az account set --subscription $(AZURE_SUBSCRIPTION)'
  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      backendServiceArm: 'azurerm-connection'
      backendAzureRmResourceGroupName: '$(RESOURCE_GROUP_NAME)'
      backendAzureRmStorageAccountName: '$(STORAGE_ACCOUNT_NAME)'
      backendAzureRmContainerName: '$(CONTAINER_NAME)'
      backendAzureRmKey: '$(AZURERM_KEY)'
  - task: TerraformTaskV4@4
    displayName: 'Terraform Validate'
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      environmentServiceNameAzureRM: 'azurerm-connection'
    env:
      TF_VAR_sp_tenant_id: $(AZURE_TENANT_ID)
      TF_VAR_sp_client_id: $(AZURE_CLIENT_ID)
      TF_VAR_sp_client_secret: $(AZURE_CLIENT_SECRET)
      TF_VAR_azure_subscription: $(AZURE_SUBSCRIPTION)

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      commandOptions: '--auto-approve'
      environmentServiceNameAzureRM: <<your_azure_devops_service_connection_name>> # TODO: replace
    env:
      TF_VAR_sp_tenant_id: $(AZURE_TENANT_ID)
      TF_VAR_sp_client_id: $(AZURE_CLIENT_ID)
      TF_VAR_sp_client_secret: $(AZURE_CLIENT_SECRET)
      TF_VAR_azure_subscription: $(AZURE_SUBSCRIPTION)
